/*EXPECTED SIX MONTH DEATH RATES*/
DATA PROJECT2.SIXMONTHRATES;
  SET PROJECT2.RECENTPERIOD;
  BY HOSPCODE NOTSORTED;
  IF FIRST.HOSPCODE then SUMBYHOSPCODE=0;
    SUMBYHOSPCODE+DEATH30;
RUN;
PROC PRINT DATA = PROJECT2.SIXMONTHRATES;
RUN;

PROC FREQ DATA = PROJECT2.SIXMONTHRATES;
TABLES HOSPCODE*SUMBYHOSPCODE;
RUN;

PROC FREQ DATA = PROJECT2.SIXMONTHRATES;
TABLES HOSPCODE*DEATH30 / CMH;
RUN;


/*OBSERVED DEATH RATE ANALYSIS*/
PROC LOGISTIC DATA=PROJECT2.CLEAN PLOTS=ALL;
CLASS PROCED LEVEL;
MODEL DEATH30 (EVENT = '1')=PROCED LEVEL ALBUMIN BMICALC;
OUTPUT OUT=PROJECT2.EXPECTEDALBUMIN PREDICTED=ESTPROB L=LOWER95 U=UPPER95;
RUN;

/*WITHOUT ALBUMIN*/
PROC LOGISTIC DATA=PROJECT2.CLEAN PLOTS=ALL;
CLASS PROCED LEVEL;
MODEL DEATH30 (EVENT = '1')=PROCED LEVEL BMICALC;
OUTPUT OUT=PROJECT2.EXPECTED PREDICTED=PREDPROB L=LOWER95 U=UPPER95;
RUN;

/*EXPECTED RATE CALCULATION*/
PROC MEANS DATA=PROJECT2.EXPECTED;
VAR PREDPROB;
BY HOSPCODE;
OUTPUT OUT=PROJECT2.EXPECTED2 MEAN=;
RUN;

PROC MEANS DATA=PROJECT2.EXPECTED;
VAR PREDPROB;
BY HOSPCODE;
OUTPUT OUT=PROJECT2.EXPECTEDALBUMIN2 MEAN=;
RUN;
