/**************************************************************************
******HEADER***************************************************************
******DATE: 8 NOVEMBER 2017************************************************
******SAS EDITION 9.4******************************************************
******PURPOSE: THIS PROGRAM CONTAINS THE DESCRIPTIVES**********************
************** AND ANALYSIS PORTION FOR PROJECT 3**************************
******OWNER: KAYLA BELL****************************************************/

/*ANIMALS MODEL: REPEATED MEASURES*/
PROC MIXED DATA = WORK.P3CLEAN;
CLASS ID SEX DEMIND;
MODEL ANIMALS = SEX DEMIND SOCI0 AGENEW CHANGEANL /SOLUTION;
REPEATED/SUBJECT=ID TYPE=CS R RCORR;
RUN;

PROC MIXED DATA = WORK.P3CLEAN; /*WITH INTERACTION*/
CLASS ID SEX DEMIND;
MODEL ANIMALS = SEX DEMIND SOCI0 AGENEW AGENEW*DEMIND CHANGEANL /SOLUTION;
REPEATED/SUBJECT=ID TYPE=CS R RCORR;
RUN;

/*ANIMALS MODEL: RANDOM INTERCEPT*/
PROC MIXED DATA = WORK.P3CLEAN PLOTS = ALL;
CLASS ID SEX DEMIND ;
MODEL ANIMALS= SEX DEMIND SOCI0 AGENEW AGENEW*DEMIND CHANGEANL /SOLUTION;
RANDOM INTERCEPT  / SUBJECT = ID TYPE = UN G GCORR V VCORR;
RUN;

/*ANIMALS MODEL: RANDOM SLOPE*/
PROC MIXED DATA = WORK.P3CLEAN PLOTS = ALL;
CLASS ID SEX DEMIND ;
MODEL ANIMALS= SEX DEMIND SOCI0 AGENEW AGENEW*DEMIND CHANGEANL /SOLUTION;
RANDOM AGENEW  / SUBJECT = ID TYPE = UN G GCORR V VCORR;
RUN;

/*ANIMALS MODEL: RANDOM INTERCEPT/SLOPE*/
PROC MIXED DATA = WORK.P3CLEAN PLOTS = ALL;
CLASS ID SEX DEMIND ;
MODEL ANIMALS= SEX DEMIND SOCI0 AGENEW AGENEW*DEMIND CHANGEANL /SOLUTION CL;
RANDOM INTERCEPT AGENEW  / SUBJECT = ID TYPE = UN G GCORR V VCORR;
RUN;
