/*Importing the data*/
PROC IMPORT OUT= WORK.hiv 
            DATAFILE= "C:\Users\Kayla\Desktop\hiv_6623_final.csv" 
            DBMS=CSV REPLACE;
     GETNAMES=YES;
     DATAROW=2; 
RUN;

PROC CONTENTS DATA = hiv;
RUN;

/*Correcting missing values, character to numeric variables, and cleaning the dataset*/
DATA WORK.HIV;
SET WORK.HIV;
ARRAY CHANGE _CHARACTER_;
            DO OVER change;
            IF change="NA" THEN change=.;
            END;
RUN;

DATA WORK.HIV;
SET WORK.HIV;
ADHNUM = INPUT(ADH, BEST12.);
BMINUM = INPUT(BMI, BEST12.); 
HASHVNUM = INPUT(HASHV, BEST12.);
LDLNUM = INPUT(LDL, BEST12.);
LEU3NUM = INPUT(LEU3N, BEST12.);
TCHOLNUM = INPUT(TCHOL, BEST12.);
TRIGNUM = INPUT(TRIG, BEST12.);
VLOADNUM = INPUT(VLOAD, BEST12.);
RUN;

DATA WORK.HIVNEW;
SET WORK.HIV;
DROP ADH BMI HASHV LDL LEU3N TCHOL TRIG VLOAD;
RUN;

/*Deleting Years > 2*/
DATA WORK.HIVNEW;
SET WORK.HIVNEW;
IF YEARS > 2 THEN DELETE;
RUN;

DATA WORK.HIVNEW;
SET WORK.HIVNEW;
LOGVLOAD = LOG10(VLOADNUM);
RUN;

DATA WORK.HIVNEW;
SET WORK.HIVNEW;
DROP OLDID HBP DIAB LIV34 KID FRP FP DYSLIP CESD HEROPIATE IDU HIVPOS VLOADNUM TRIGNUM TCHOLNUM HASHVNUM LDLNUM;
RUN;

DATA WORK.HIVBASELINEYEAR;
SET WORK.HIVNEW;
IF YEARS > 0 THEN DELETE;
RUN;

DATA WORK.HIVBASELINEYEAR;
SET WORK.HIVBASELINEYEAR;
MENTALBASE = AGG_MENT;
PHYSICALBASE = AGG_PHYS;
LEUBASE = LEU3NUM;
VLOADBASE = LOGVLOAD;
BASEMJ = HASHF;
RUN;

DATA WORK.HIVBASELINEYEAR;
SET WORK.HIVBASELINEYEAR;
IF DKGRP = 0 OR DKGRP = 1 OR DKGRP = 2 THEN BASEALC = 0; IF DKGRP = 3 THEN BASEALC = 1;
IF SMOKE = 1 OR SMOKE = 2 THEN CURRENTSMOKE = 0; IF SMOKE = 3 THEN CURRENTSMOKE = 1; IF SMOKE = . THEN CURRENTSMOKE = .;
IF RACE = 1 THEN NHW = 1; IF RACE = 2 OR RACE = 3 OR RACE =4
OR RACE = 5 OR RACE = 6 OR RACE = 7 OR RACE = 8 THEN NHW = 0; IF RACE = . THEN NHW = .;
IF INCOME = 1 OR INCOME = 2 OR INCOME = 3 OR INCOME = 4 THEN SALARY = 0; 
IF INCOME = 4 OR INCOME = 5 OR INCOME = 6 OR INCOME =7 THEN SALARY = 1; IF INCOME = 9 THEN SALARY = .; 
IF INCOME = . THEN SALARY = .;
IF EDUCBAS = 1 OR EDUCBAS = 2 OR EDUCBAS = 3 THEN EDUC = 0; 
IF EDUCBAS = 4 OR EDUCBAS = 5 OR EDUCBAS = 6 OR EDUCBAS = 7 THEN EDUC = 1; IF EDUCBAS = . THEN EDUC = .;
RUN;

DATA WORK.HIVBASELINEYEAR;
SET WORK.HIVBASELINEYEAR;
DROP YEARS ART EVERART DKGRP SMOKE RACE INCOME EDUCBAS ADHNUM HASHF AGG_MENT AGG_PHYS LEU3NUM LOGVLOAD;
RUN;

DATA WORK.HIVYEAR2;
SET WORK.HIVNEW;
IF YEARS < 2 THEN DELETE;
RUN;

DATA WORK.HIVYEAR2;
SET WORK.HIVYEAR2;
MENTALFINAL = AGG_MENT;
PHYSICALFINAL = AGG_PHYS;
LEUFINAL = LEU3NUM;
VLOADFINAL = LOGVLOAD;
IF ADHNUM = 1 OR ADHNUM = 2 THEN HARTADH = 1; IF ADHNUM = 3 OR ADHNUM = 4 THEN HARTADH = 0;
IF ADHNUM = . THEN HARTADH = .; 
RUN;

DATA WORK.HIVYEAR2;
SET WORK.HIVYEAR2;
DROP YEARS HASHF INCOME SMOKE DKGRP RACE EDUCBAS ADHNUM ART EVERART AGG_MENT AGG_PHYS LEU3NUM LOGVLOAD;
RUN;

DATA WORK.HIVCLEAN;
MERGE WORK.HIVBASELINEYEAR WORK.HIVYEAR2;
BY NEWID;
RUN;

DATA WORK.HIVCLEAN;
SET WORK.HIVCLEAN;
DMENTAL = MENTALBASE-MENTALFINAL;
DPHYSICAL = PHYSICALBASE-PHYSICALFINAL;
DLEU = LEUBASE-LEUFINAL;
DVLOAD = VLOADBASE-VLOADFINAL;
RUN;

DATA WORK.HIVCLEAN;
SET WORK.HIVCLEAN;
IF MISSING(MENTALBASE) THEN DELETE;
IF MISSING(PHYSICALBASE) THEN DELETE;
IF MISSING (LEUBASE) THEN DELETE;
IF MISSING(VLOADBASE) THEN DELETE;
IF MISSING (MENTALFINAL)THEN DELETE;
IF MISSING(PHYSICALFINAL) THEN DELETE;
IF MISSING (LEUFINAL) THEN DELETE;
IF MISSING(VLOADFINAL) THEN DELETE;
RUN;


 
