/*********Header*******************************************************************
**** This program contains part 1 of code for Project 1 \: HAART Data Analysis*****
**** Date: October 9, 2017*********************************************************
**** SAS Edition 9.4***************************************************************
**** Purpose: to analyze the data**************************************************
**** Owner: Kayla Bell*************************************************************/

/*Viewing outcome distributions*/
PROC UNIVARIATE DATA = WORK.HIVCLEAN PLOTS;
VAR DMENTAL DPHYSICAL DLEU DVLOAD;
RUN;

/*Individual associations*/
PROC REG DATA = WORK.HIVCLEAN;
MODEL DMENTAL = MENTALBASE;
RUN; 
PROC REG DATA = WORK.HIVCLEAN;
MODEL DMENTAL = BMINUM;
RUN; 
PROC REG DATA = WORK.HIVCLEAN;
MODEL DMENTAL = AGE;
RUN; 
PROC REG DATA = WORK.HIVCLEAN;
MODEL DMENTAL = NHW;
RUN;
PROC REG DATA = WORK.HIVCLEAN;
MODEL DMENTAL = HARD_DRUGS;
RUN;
PROC REG DATA = WORK.HIVCLEAN;
MODEL DMENTAL = BASEALC;
RUN;
PROC REG DATA = WORK.HIVCLEAN;
MODEL DMENTAL = CURRENTSMOKE;
RUN;
PROC REG DATA = WORK.HIVCLEAN;
MODEL DMENTAL = SALARY;
RUN;
PROC REG DATA = WORK.HIVCLEAN;
MODEL DMENTAL = EDUC;
RUN;
PROC REG DATA = WORK.HIVCLEAN;
MODEL DMENTAL = HARTADH;
RUN;
PROC REG DATA = WORK.HIVCLEAN;
MODEL DMENTAL = BASEMJUSE;
RUN;

/*Model for difference in mental score*/
PROC GLM DATA = WORK.HIVCLEAN;
CLASS HARD_DRUGS NHW;
MODEL DMENTAL = HARD_DRUGS MENTALBASE NHW / CLPARM SOLUTIONS;
RUN;

PROC GLM DATA = WORK.HIVCLEAN; /*Final model for DMENTAL*/
CLASS NHW;
MODEL DMENTAL = MENTALBASE NHW / SOLUTIONS;
RUN;

/*Model for DPHYSICAL*/
PROC GLM DATA = WORK.HIVCLEAN;
CLASS HARD_DRUGS BASEALC CURRENTSMOKE NHW SALARY EDUC HARTADH BASEMJUSE;
MODEL DPHYSICAL = AGE HARD_DRUGS BMINUM PHYSICALBASE BASEALC CURRENTSMOKE NHW SALARY EDUC HARTADH BASEMJUSE / SOLUTIONS;
RUN;

PROC GLM DATA = WORK.HIVCLEAN;
CLASS HARD_DRUGS BASEALC NHW EDUC HARTADH BASEMJUSE;
MODEL DPHYSICAL = AGE HARD_DRUGS BMINUM PHYSICALBASE BASEALC NHW EDUC HARTADH BASEMJUSE / SOLUTIONS;
RUN;

PROC GLM DATA = WORK.HIVCLEAN;
CLASS HARD_DRUGS BASEALC EDUC HARTADH;
MODEL DPHYSICAL = AGE HARD_DRUGS BMINUM PHYSICALBASE BASEALC EDUC HARTADH / SOLUTIONS;
RUN;


PROC GLM DATA = WORK.HIVCLEAN; /*Final model for aggregate physical score difference*/
CLASS HARD_DRUGS EDUC HARTADH;
MODEL DPHYSICAL = AGE HARD_DRUGS PHYSICALBASE EDUC HARTADH / CLPARM SOLUTIONS;
RUN;

/*Model for DLEU*/
PROC GLM DATA = WORK.HIVCLEAN;
CLASS HARD_DRUGS BASEALC CURRENTSMOKE NHW SALARY EDUC HARTADH BASEMJUSE;
MODEL DLEU = AGE HARD_DRUGS BMINUM LEUBASE BASEALC CURRENTSMOKE NHW SALARY EDUC HARTADH BASEMJUSE / SOLUTIONS;
RUN;

PROC GLM DATA = WORK.HIVCLEAN; 
CLASS HARD_DRUGS SALARY EDUC HARTADH;
MODEL DLEU = HARD_DRUGS BMINUM SALARY EDUC HARTADH / CLPARM SOLUTIONS;
RUN;

PROC GLM DATA = WORK.HIVCLEAN; /*Final model for DLEU*/
CLASS HARD_DRUGS SALARY EDUC;
MODEL DLEU = HARD_DRUGS BMINUM SALARY EDUC / CLPARM SOLUTIONS;
RUN;

PROC GLM DATA = WORK.HIVCLEAN;
CLASS HARD_DRUGS EDUC;
MODEL DLEU = HARD_DRUGS BMINUM EDUC / CLPARM SOLUTIONS;
RUN;

/*Model for viral load*/
PROC GLM DATA = WORK.HIVCLEAN;
CLASS HARD_DRUGS BASEALC CURRENTSMOKE NHW SALARY EDUC HARTADH BASEMJUSE;
MODEL DVLOAD = AGE HARD_DRUGS BMINUM VLOADBASE BASEALC CURRENTSMOKE NHW SALARY EDUC HARTADH BASEMJUSE / SOLUTIONS;
RUN;

PROC GLM DATA = WORK.HIVCLEAN; /*Final model for viral load*/
CLASS HARD_DRUGS NHW SALARY EDUC HARTADH BASEMJUSE;
MODEL DVLOAD = HARD_DRUGS VLOADBASE NHW SALARY EDUC HARTADH / CLPARM SOLUTIONS;
RUN;


